// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.1
// source: ChoiCourse.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type CourseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CourseRequest) Reset() {
	*x = CourseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseRequest) ProtoMessage() {}

func (x *CourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseRequest.ProtoReflect.Descriptor instead.
func (*CourseRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{0}
}

// 响应消息
type CourseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CId         int64  `protobuf:"varint,1,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
	CName       string `protobuf:"bytes,2,opt,name=c_name,json=cName,proto3" json:"c_name,omitempty"`
	Info        string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	TeacherId   int64  `protobuf:"varint,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	TeacherName string `protobuf:"bytes,5,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
}

func (x *CourseReply) Reset() {
	*x = CourseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseReply) ProtoMessage() {}

func (x *CourseReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseReply.ProtoReflect.Descriptor instead.
func (*CourseReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{1}
}

func (x *CourseReply) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

func (x *CourseReply) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *CourseReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *CourseReply) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CourseReply) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

type CourseReplyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*CourseReply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"` // 包含一个或多个CourseReply消息
}

func (x *CourseReplyList) Reset() {
	*x = CourseReplyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseReplyList) ProtoMessage() {}

func (x *CourseReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseReplyList.ProtoReflect.Descriptor instead.
func (*CourseReplyList) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{2}
}

func (x *CourseReplyList) GetReplies() []*CourseReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

// 根据课程名搜索课程
type SearchACRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CName string `protobuf:"bytes,1,opt,name=c_name,json=cName,proto3" json:"c_name,omitempty"`
}

func (x *SearchACRequest) Reset() {
	*x = SearchACRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchACRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchACRequest) ProtoMessage() {}

func (x *SearchACRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchACRequest.ProtoReflect.Descriptor instead.
func (*SearchACRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{3}
}

func (x *SearchACRequest) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

type SearchACReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CId         int64  `protobuf:"varint,1,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
	CName       string `protobuf:"bytes,2,opt,name=c_name,json=cName,proto3" json:"c_name,omitempty"`
	Info        string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	TeacherId   int64  `protobuf:"varint,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	TeacherName string `protobuf:"bytes,5,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
}

func (x *SearchACReply) Reset() {
	*x = SearchACReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchACReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchACReply) ProtoMessage() {}

func (x *SearchACReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchACReply.ProtoReflect.Descriptor instead.
func (*SearchACReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{4}
}

func (x *SearchACReply) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

func (x *SearchACReply) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *SearchACReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *SearchACReply) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *SearchACReply) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

type SearchACReplyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*SearchACReply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
}

func (x *SearchACReplyList) Reset() {
	*x = SearchACReplyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchACReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchACReplyList) ProtoMessage() {}

func (x *SearchACReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchACReplyList.ProtoReflect.Descriptor instead.
func (*SearchACReplyList) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{5}
}

func (x *SearchACReplyList) GetReplies() []*SearchACReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

// 显示已选课的信息
type SearchERequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuId int64 `protobuf:"varint,1,opt,name=stu_id,json=stuId,proto3" json:"stu_id,omitempty"`
}

func (x *SearchERequest) Reset() {
	*x = SearchERequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchERequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchERequest) ProtoMessage() {}

func (x *SearchERequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchERequest.ProtoReflect.Descriptor instead.
func (*SearchERequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{6}
}

func (x *SearchERequest) GetStuId() int64 {
	if x != nil {
		return x.StuId
	}
	return 0
}

type SearchEReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CId         int64  `protobuf:"varint,1,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
	CName       string `protobuf:"bytes,2,opt,name=c_name,json=cName,proto3" json:"c_name,omitempty"`
	Info        string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	TeacherId   int64  `protobuf:"varint,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	TeacherName string `protobuf:"bytes,5,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
}

func (x *SearchEReply) Reset() {
	*x = SearchEReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEReply) ProtoMessage() {}

func (x *SearchEReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEReply.ProtoReflect.Descriptor instead.
func (*SearchEReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{7}
}

func (x *SearchEReply) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

func (x *SearchEReply) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *SearchEReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *SearchEReply) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *SearchEReply) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

type SearchEReplyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*SearchEReply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
}

func (x *SearchEReplyList) Reset() {
	*x = SearchEReplyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEReplyList) ProtoMessage() {}

func (x *SearchEReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEReplyList.ProtoReflect.Descriptor instead.
func (*SearchEReplyList) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{8}
}

func (x *SearchEReplyList) GetReplies() []*SearchEReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

// 删除已选的课
type SdelCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuId int64 `protobuf:"varint,1,opt,name=stu_id,json=stuId,proto3" json:"stu_id,omitempty"`
	CId   int64 `protobuf:"varint,2,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
}

func (x *SdelCRequest) Reset() {
	*x = SdelCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdelCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdelCRequest) ProtoMessage() {}

func (x *SdelCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdelCRequest.ProtoReflect.Descriptor instead.
func (*SdelCRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{9}
}

func (x *SdelCRequest) GetStuId() int64 {
	if x != nil {
		return x.StuId
	}
	return 0
}

func (x *SdelCRequest) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

type SdelCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SdelCReply) Reset() {
	*x = SdelCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdelCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdelCReply) ProtoMessage() {}

func (x *SdelCReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdelCReply.ProtoReflect.Descriptor instead.
func (*SdelCReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{10}
}

func (x *SdelCReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// 添加选课
type SputCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StuId int64 `protobuf:"varint,1,opt,name=stu_id,json=stuId,proto3" json:"stu_id,omitempty"`
	CId   int64 `protobuf:"varint,2,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
}

func (x *SputCRequest) Reset() {
	*x = SputCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SputCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SputCRequest) ProtoMessage() {}

func (x *SputCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SputCRequest.ProtoReflect.Descriptor instead.
func (*SputCRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{11}
}

func (x *SputCRequest) GetStuId() int64 {
	if x != nil {
		return x.StuId
	}
	return 0
}

func (x *SputCRequest) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

// 响应消息
type SputCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SputCReply) Reset() {
	*x = SputCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SputCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SputCReply) ProtoMessage() {}

func (x *SputCReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SputCReply.ProtoReflect.Descriptor instead.
func (*SputCReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{12}
}

func (x *SputCReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// 请求消息
type TputCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TId   int64  `protobuf:"varint,1,opt,name=t_id,json=tId,proto3" json:"t_id,omitempty"`
	TName string `protobuf:"bytes,2,opt,name=t_name,json=tName,proto3" json:"t_name,omitempty"`
	CId   int64  `protobuf:"varint,3,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
	CName string `protobuf:"bytes,4,opt,name=c_name,json=cName,proto3" json:"c_name,omitempty"`
	Info  string `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *TputCRequest) Reset() {
	*x = TputCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TputCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TputCRequest) ProtoMessage() {}

func (x *TputCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TputCRequest.ProtoReflect.Descriptor instead.
func (*TputCRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{13}
}

func (x *TputCRequest) GetTId() int64 {
	if x != nil {
		return x.TId
	}
	return 0
}

func (x *TputCRequest) GetTName() string {
	if x != nil {
		return x.TName
	}
	return ""
}

func (x *TputCRequest) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

func (x *TputCRequest) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *TputCRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type TputCRequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*TputCRequest `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
}

func (x *TputCRequestList) Reset() {
	*x = TputCRequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TputCRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TputCRequestList) ProtoMessage() {}

func (x *TputCRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TputCRequestList.ProtoReflect.Descriptor instead.
func (*TputCRequestList) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{14}
}

func (x *TputCRequestList) GetReplies() []*TputCRequest {
	if x != nil {
		return x.Replies
	}
	return nil
}

// 响应消息
type TputCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *TputCReply) Reset() {
	*x = TputCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TputCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TputCReply) ProtoMessage() {}

func (x *TputCReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TputCReply.ProtoReflect.Descriptor instead.
func (*TputCReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{15}
}

func (x *TputCReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// 一组
type TupdateCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TId   int64  `protobuf:"varint,1,opt,name=t_id,json=tId,proto3" json:"t_id,omitempty"`
	TName string `protobuf:"bytes,2,opt,name=t_name,json=tName,proto3" json:"t_name,omitempty"`
	CId   int64  `protobuf:"varint,3,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
	CName string `protobuf:"bytes,4,opt,name=c_name,json=cName,proto3" json:"c_name,omitempty"`
	Info  string `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *TupdateCRequest) Reset() {
	*x = TupdateCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TupdateCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupdateCRequest) ProtoMessage() {}

func (x *TupdateCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupdateCRequest.ProtoReflect.Descriptor instead.
func (*TupdateCRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{16}
}

func (x *TupdateCRequest) GetTId() int64 {
	if x != nil {
		return x.TId
	}
	return 0
}

func (x *TupdateCRequest) GetTName() string {
	if x != nil {
		return x.TName
	}
	return ""
}

func (x *TupdateCRequest) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

func (x *TupdateCRequest) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *TupdateCRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type TupdateCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *TupdateCReply) Reset() {
	*x = TupdateCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TupdateCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupdateCReply) ProtoMessage() {}

func (x *TupdateCReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupdateCReply.ProtoReflect.Descriptor instead.
func (*TupdateCReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{17}
}

func (x *TupdateCReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// 一组
type TdeleteCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TId int64 `protobuf:"varint,1,opt,name=t_id,json=tId,proto3" json:"t_id,omitempty"`
	CId int64 `protobuf:"varint,2,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
}

func (x *TdeleteCRequest) Reset() {
	*x = TdeleteCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TdeleteCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TdeleteCRequest) ProtoMessage() {}

func (x *TdeleteCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TdeleteCRequest.ProtoReflect.Descriptor instead.
func (*TdeleteCRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{18}
}

func (x *TdeleteCRequest) GetTId() int64 {
	if x != nil {
		return x.TId
	}
	return 0
}

func (x *TdeleteCRequest) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

// 响应消息
type TdeleteCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *TdeleteCReply) Reset() {
	*x = TdeleteCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TdeleteCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TdeleteCReply) ProtoMessage() {}

func (x *TdeleteCReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TdeleteCReply.ProtoReflect.Descriptor instead.
func (*TdeleteCReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{19}
}

func (x *TdeleteCReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type TgetCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TId int64 `protobuf:"varint,1,opt,name=t_id,json=tId,proto3" json:"t_id,omitempty"`
}

func (x *TgetCRequest) Reset() {
	*x = TgetCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgetCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgetCRequest) ProtoMessage() {}

func (x *TgetCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgetCRequest.ProtoReflect.Descriptor instead.
func (*TgetCRequest) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{20}
}

func (x *TgetCRequest) GetTId() int64 {
	if x != nil {
		return x.TId
	}
	return 0
}

type TgetCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TId    int64  `protobuf:"varint,1,opt,name=t_id,json=tId,proto3" json:"t_id,omitempty"`
	TName  string `protobuf:"bytes,2,opt,name=t_name,json=tName,proto3" json:"t_name,omitempty"`
	CId    int64  `protobuf:"varint,3,opt,name=c_id,json=cId,proto3" json:"c_id,omitempty"`
	CName  string `protobuf:"bytes,4,opt,name=c_name,json=cName,proto3" json:"c_name,omitempty"`
	Info   string `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	Respon string `protobuf:"bytes,6,opt,name=respon,proto3" json:"respon,omitempty"`
}

func (x *TgetCReply) Reset() {
	*x = TgetCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgetCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgetCReply) ProtoMessage() {}

func (x *TgetCReply) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgetCReply.ProtoReflect.Descriptor instead.
func (*TgetCReply) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{21}
}

func (x *TgetCReply) GetTId() int64 {
	if x != nil {
		return x.TId
	}
	return 0
}

func (x *TgetCReply) GetTName() string {
	if x != nil {
		return x.TName
	}
	return ""
}

func (x *TgetCReply) GetCId() int64 {
	if x != nil {
		return x.CId
	}
	return 0
}

func (x *TgetCReply) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *TgetCReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *TgetCReply) GetRespon() string {
	if x != nil {
		return x.Respon
	}
	return ""
}

type TgetCReplyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*TgetCReply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
}

func (x *TgetCReplyList) Reset() {
	*x = TgetCReplyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChoiCourse_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgetCReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgetCReplyList) ProtoMessage() {}

func (x *TgetCReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_ChoiCourse_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgetCReplyList.ProtoReflect.Descriptor instead.
func (*TgetCReplyList) Descriptor() ([]byte, []int) {
	return file_ChoiCourse_proto_rawDescGZIP(), []int{22}
}

func (x *TgetCReplyList) GetReplies() []*TgetCReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

var File_ChoiCourse_proto protoreflect.FileDescriptor

var file_ChoiCourse_proto_rawDesc = []byte{
	0x0a, 0x10, 0x43, 0x68, 0x6f, 0x69, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x0f, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x07, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41,
	0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x8f, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x43, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x63, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x40, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x43, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x41, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x74, 0x75, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x75, 0x49, 0x64, 0x22, 0x8e, 0x01, 0x0a,
	0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x11, 0x0a,
	0x04, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x22, 0x38, 0x0a,
	0x0c, 0x53, 0x64, 0x65, 0x6c, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x74, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x74, 0x75, 0x49, 0x64, 0x12, 0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x63, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x64, 0x65, 0x6c, 0x43,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x38, 0x0a, 0x0c, 0x53, 0x70, 0x75,
	0x74, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x74, 0x75,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x75, 0x49, 0x64,
	0x12, 0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x63, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x76, 0x0a, 0x0c, 0x54, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3e, 0x0a,
	0x10, 0x54, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x22, 0x20, 0x0a,
	0x0a, 0x54, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22,
	0x79, 0x0a, 0x0f, 0x54, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x11, 0x0a, 0x04,
	0x63, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x49, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x54, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22,
	0x37, 0x0a, 0x0f, 0x54, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x74, 0x49, 0x64, 0x12, 0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0d, 0x54, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x21, 0x0a,
	0x0c, 0x54, 0x67, 0x65, 0x74, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x11, 0x0a,
	0x04, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x49, 0x64,
	0x22, 0x8c, 0x01, 0x0a, 0x0a, 0x54, 0x67, 0x65, 0x74, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x11, 0x0a, 0x04, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x11, 0x0a, 0x04, 0x63, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x22,
	0x3a, 0x0a, 0x0e, 0x54, 0x67, 0x65, 0x74, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x67, 0x65, 0x74, 0x43, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x32, 0xf7, 0x03, 0x0a, 0x0a,
	0x67, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x09, 0x67, 0x65,
	0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x3d, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x43,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x41, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c,
	0x0a, 0x10, 0x67, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x45, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0d,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x64, 0x65, 0x6c, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x64, 0x65, 0x6c, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2e, 0x0a, 0x0a, 0x70, 0x75, 0x74, 0x53, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2e, 0x0a, 0x0a, 0x70, 0x75, 0x74, 0x54, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x70, 0x75, 0x74, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x37, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x54,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x32, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x54, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x67, 0x65, 0x74, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x67, 0x65, 0x74, 0x43, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ChoiCourse_proto_rawDescOnce sync.Once
	file_ChoiCourse_proto_rawDescData = file_ChoiCourse_proto_rawDesc
)

func file_ChoiCourse_proto_rawDescGZIP() []byte {
	file_ChoiCourse_proto_rawDescOnce.Do(func() {
		file_ChoiCourse_proto_rawDescData = protoimpl.X.CompressGZIP(file_ChoiCourse_proto_rawDescData)
	})
	return file_ChoiCourse_proto_rawDescData
}

var file_ChoiCourse_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ChoiCourse_proto_goTypes = []interface{}{
	(*CourseRequest)(nil),     // 0: pb.CourseRequest
	(*CourseReply)(nil),       // 1: pb.CourseReply
	(*CourseReplyList)(nil),   // 2: pb.CourseReplyList
	(*SearchACRequest)(nil),   // 3: pb.SearchACRequest
	(*SearchACReply)(nil),     // 4: pb.SearchACReply
	(*SearchACReplyList)(nil), // 5: pb.SearchACReplyList
	(*SearchERequest)(nil),    // 6: pb.SearchERequest
	(*SearchEReply)(nil),      // 7: pb.SearchEReply
	(*SearchEReplyList)(nil),  // 8: pb.SearchEReplyList
	(*SdelCRequest)(nil),      // 9: pb.SdelCRequest
	(*SdelCReply)(nil),        // 10: pb.SdelCReply
	(*SputCRequest)(nil),      // 11: pb.SputCRequest
	(*SputCReply)(nil),        // 12: pb.SputCReply
	(*TputCRequest)(nil),      // 13: pb.TputCRequest
	(*TputCRequestList)(nil),  // 14: pb.TputCRequestList
	(*TputCReply)(nil),        // 15: pb.TputCReply
	(*TupdateCRequest)(nil),   // 16: pb.TupdateCRequest
	(*TupdateCReply)(nil),     // 17: pb.TupdateCReply
	(*TdeleteCRequest)(nil),   // 18: pb.TdeleteCRequest
	(*TdeleteCReply)(nil),     // 19: pb.TdeleteCReply
	(*TgetCRequest)(nil),      // 20: pb.TgetCRequest
	(*TgetCReply)(nil),        // 21: pb.TgetCReply
	(*TgetCReplyList)(nil),    // 22: pb.TgetCReplyList
}
var file_ChoiCourse_proto_depIdxs = []int32{
	1,  // 0: pb.CourseReplyList.replies:type_name -> pb.CourseReply
	4,  // 1: pb.SearchACReplyList.replies:type_name -> pb.SearchACReply
	7,  // 2: pb.SearchEReplyList.replies:type_name -> pb.SearchEReply
	13, // 3: pb.TputCRequestList.replies:type_name -> pb.TputCRequest
	21, // 4: pb.TgetCReplyList.replies:type_name -> pb.TgetCReply
	0,  // 5: pb.getGreeter.getCourse:input_type -> pb.CourseRequest
	3,  // 6: pb.getGreeter.getSearchCourse:input_type -> pb.SearchACRequest
	6,  // 7: pb.getGreeter.getSearchECourse:input_type -> pb.SearchERequest
	9,  // 8: pb.getGreeter.deleteSCourse:input_type -> pb.SdelCRequest
	11, // 9: pb.getGreeter.putSCourse:input_type -> pb.SputCRequest
	13, // 10: pb.getGreeter.putTCourse:input_type -> pb.TputCRequest
	16, // 11: pb.getGreeter.updateTCourse:input_type -> pb.TupdateCRequest
	18, // 12: pb.getGreeter.deleteTCourse:input_type -> pb.TdeleteCRequest
	20, // 13: pb.getGreeter.getTCourse:input_type -> pb.TgetCRequest
	2,  // 14: pb.getGreeter.getCourse:output_type -> pb.CourseReplyList
	5,  // 15: pb.getGreeter.getSearchCourse:output_type -> pb.SearchACReplyList
	8,  // 16: pb.getGreeter.getSearchECourse:output_type -> pb.SearchEReplyList
	10, // 17: pb.getGreeter.deleteSCourse:output_type -> pb.SdelCReply
	12, // 18: pb.getGreeter.putSCourse:output_type -> pb.SputCReply
	15, // 19: pb.getGreeter.putTCourse:output_type -> pb.TputCReply
	17, // 20: pb.getGreeter.updateTCourse:output_type -> pb.TupdateCReply
	19, // 21: pb.getGreeter.deleteTCourse:output_type -> pb.TdeleteCReply
	22, // 22: pb.getGreeter.getTCourse:output_type -> pb.TgetCReplyList
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ChoiCourse_proto_init() }
func file_ChoiCourse_proto_init() {
	if File_ChoiCourse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ChoiCourse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseReplyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchACRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchACReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchACReplyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchERequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchEReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchEReplyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdelCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdelCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SputCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SputCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TputCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TputCRequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TputCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TupdateCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TupdateCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TdeleteCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TdeleteCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgetCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgetCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChoiCourse_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgetCReplyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ChoiCourse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ChoiCourse_proto_goTypes,
		DependencyIndexes: file_ChoiCourse_proto_depIdxs,
		MessageInfos:      file_ChoiCourse_proto_msgTypes,
	}.Build()
	File_ChoiCourse_proto = out.File
	file_ChoiCourse_proto_rawDesc = nil
	file_ChoiCourse_proto_goTypes = nil
	file_ChoiCourse_proto_depIdxs = nil
}
