// Code generated by goctl. DO NOT EDIT.
package handler

import (
	UserController2 "github.com/moker/app/usercenter/cmd/api/internal/handler/UserController"
	"github.com/moker/app/usercenter/cmd/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/vercode",
				Handler: UserController2.VerCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserController2.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: UserController2.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/moker/v1"),
	)
}
