// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	UserCenter "github.com/moker/app/usercenter/cmd/api/internal/handler/UserCenter"
	UserController "github.com/moker/app/usercenter/cmd/api/internal/handler/UserController"
	"github.com/moker/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/vercode",
				Handler: UserController.VerCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserController.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: UserController.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/moker/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/userinfo",
				Handler: UserCenter.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/userinfo",
				Handler: UserCenter.UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/userinfo",
				Handler: UserCenter.DeleteUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/swift/v1"),
	)
}
