// Code generated by goctl. DO NOT EDIT.

package role

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/moker/common/globalkey"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	studentsFieldNames          = builder.RawFieldNames(&Students{})
	studentsRows                = strings.Join(studentsFieldNames, ",")
	studentsRowsExpectAutoSet   = strings.Join(stringx.Remove(studentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	studentsRowsWithPlaceHolder = strings.Join(stringx.Remove(studentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMokerUsercenterStudentsIdPrefix       = "cache:mokerUsercenter:students:id:"
	cacheMokerUsercenterStudentsUserIdPrefix 	= "cache:mokerUsercenter:students:userId:"
	cacheMokerUsercenterStudentsIdUserIdPrefix = "cache:mokerUsercenter:students:id:userId:"
)

type (
	studentsModel interface {
		Insert(ctx context.Context,session sqlx.Session,  data *Students) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Students, error)
		FindOneByUserId(ctx context.Context, userId int64) (*Students, error)
		Update(ctx context.Context, data *Students) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStudentsModel struct {
		sqlc.CachedConn
		table string
	}

	Students struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"` // 版本号
		Name       string    `db:"name"`
		Major      string    `db:"major"`
		Faculty    string    `db:"faculty"`
		School     string    `db:"school"`
	}
)

func newStudentsModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultStudentsModel {
	return &defaultStudentsModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`students`",
	}
}

func (m *defaultStudentsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mokerUsercenterStudentsIdKey := fmt.Sprintf("%s%v", cacheMokerUsercenterStudentsIdPrefix, id)
	mokerUsercenterStudentsIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheMokerUsercenterStudentsIdUserIdPrefix, data.Id, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mokerUsercenterStudentsIdKey, mokerUsercenterStudentsIdUserIdKey)
	return err
}

func (m *defaultStudentsModel) FindOne(ctx context.Context, id int64) (*Students, error) {
	mokerUsercenterStudentsIdKey := fmt.Sprintf("%s%v", cacheMokerUsercenterStudentsIdPrefix, id)
	var resp Students
	err := m.QueryRowCtx(ctx, &resp, mokerUsercenterStudentsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", studentsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStudentsModel) FindOneByUserId(ctx context.Context, userId int64) (*Students, error) {
	mokerUsercenterStudentsUserIdKey := fmt.Sprintf("%s%v:%v", cacheMokerUsercenterStudentsUserIdPrefix, userId)
	var resp Students
	err := m.QueryRowIndexCtx(ctx, &resp, mokerUsercenterStudentsUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", studentsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStudentsModel) Insert(ctx context.Context,session sqlx.Session,  data *Students) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo
	mokerUsercenterStudentsIdKey := fmt.Sprintf("%s%v", cacheMokerUsercenterStudentsIdPrefix, data.Id)
	mokerUsercenterStudentsIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheMokerUsercenterStudentsIdUserIdPrefix, data.Id, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, studentsRowsExpectAutoSet)
		if session != nil{
			return session.ExecCtx(ctx, query, data.UserId, data.DeleteTime, data.DelState, data.Version, data.Name, data.Major, data.Faculty, data.School)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.DeleteTime, data.DelState, data.Version, data.Name, data.Major, data.Faculty, data.School)
	}, mokerUsercenterStudentsIdKey, mokerUsercenterStudentsIdUserIdKey)
	return ret, err
}

func (m *defaultStudentsModel) Update(ctx context.Context, newData *Students) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	newData.DeleteTime = time.Unix(0, 0)
	newData.DelState = globalkey.DelStateNo
	mokerUsercenterStudentsIdKey := fmt.Sprintf("%s%v", cacheMokerUsercenterStudentsIdPrefix, data.Id)
	mokerUsercenterStudentsIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheMokerUsercenterStudentsIdUserIdPrefix, data.Id, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, studentsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.DeleteTime, newData.DelState, newData.Version, newData.Name, newData.Major, newData.Faculty, newData.School, newData.Id)
	}, mokerUsercenterStudentsIdKey, mokerUsercenterStudentsIdUserIdKey)
	return err
}

func (m *defaultStudentsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMokerUsercenterStudentsIdPrefix, primary)
}

func (m *defaultStudentsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", studentsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStudentsModel) tableName() string {
	return m.table
}
