// Code generated by goctl. DO NOT EDIT.

package role

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	teachersFieldNames          = builder.RawFieldNames(&Teachers{})
	teachersRows                = strings.Join(teachersFieldNames, ",")
	teachersRowsExpectAutoSet   = strings.Join(stringx.Remove(teachersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	teachersRowsWithPlaceHolder = strings.Join(stringx.Remove(teachersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	teachersModel interface {
		Insert(ctx context.Context, data *Teachers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Teachers, error)
		FindOneByIdUserId(ctx context.Context, id int64, userId int64) (*Teachers, error)
		Update(ctx context.Context, data *Teachers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTeachersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Teachers struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"` // 版本号
		Name       string    `db:"name"`
		Faculty    string    `db:"faculty"`
		School     string    `db:"school"`
	}
)

func newTeachersModel(conn sqlx.SqlConn) *defaultTeachersModel {
	return &defaultTeachersModel{
		conn:  conn,
		table: "`teachers`",
	}
}

func (m *defaultTeachersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTeachersModel) FindOne(ctx context.Context, id int64) (*Teachers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", teachersRows, m.table)
	var resp Teachers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeachersModel) FindOneByIdUserId(ctx context.Context, id int64, userId int64) (*Teachers, error) {
	var resp Teachers
	query := fmt.Sprintf("select %s from %s where `id` = ? and `user_id` = ? limit 1", teachersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeachersModel) Insert(ctx context.Context, data *Teachers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, teachersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.DeleteTime, data.DelState, data.Version, data.Name, data.Faculty, data.School)
	return ret, err
}

func (m *defaultTeachersModel) Update(ctx context.Context, newData *Teachers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, teachersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.DeleteTime, newData.DelState, newData.Version, newData.Name, newData.Faculty, newData.School, newData.Id)
	return err
}

func (m *defaultTeachersModel) tableName() string {
	return m.table
}
