// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userSaltFieldNames          = builder.RawFieldNames(&UserSalt{})
	userSaltRows                = strings.Join(userSaltFieldNames, ",")
	userSaltRowsExpectAutoSet   = strings.Join(stringx.Remove(userSaltFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userSaltRowsWithPlaceHolder = strings.Join(stringx.Remove(userSaltFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userSaltModel interface {
		Insert(ctx context.Context, data *UserSalt) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserSalt, error)
		FindOneByUserId(ctx context.Context, userId int64) (*UserSalt, error)
		Update(ctx context.Context, data *UserSalt) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserSaltModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserSalt struct {
		Id     int64  `db:"id"`
		UserId int64  `db:"user_id"`
		Salt   string `db:"salt"` // 加密盐
	}
)

func newUserSaltModel(conn sqlx.SqlConn) *defaultUserSaltModel {
	return &defaultUserSaltModel{
		conn:  conn,
		table: "`user_salt`",
	}
}

func (m *defaultUserSaltModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserSaltModel) FindOne(ctx context.Context, id int64) (*UserSalt, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userSaltRows, m.table)
	var resp UserSalt
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSaltModel) FindOneByUserId(ctx context.Context, userId int64) (*UserSalt, error) {
	var resp UserSalt
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userSaltRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSaltModel) Insert(ctx context.Context, data *UserSalt) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userSaltRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Salt)
	return ret, err
}

func (m *defaultUserSaltModel) Update(ctx context.Context, newData *UserSalt) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userSaltRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Salt, newData.Id)
	return err
}

func (m *defaultUserSaltModel) tableName() string {
	return m.table
}
