// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/moker/app/usercenter/cmd/rpc/internal/logic"
	"github.com/moker/app/usercenter/cmd/rpc/internal/svc"
	"github.com/moker/app/usercenter/cmd/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) GetVerCode(ctx context.Context, in *pb.GetVerCodeReq) (*pb.GetVerCodeResp, error) {
	l := logic.NewGetVerCodeLogic(ctx, s.svcCtx)
	return l.GetVerCode(in)
}

func (s *UsercenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UsercenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *UsercenterServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UsercenterServer) UpdateStudentInfo(ctx context.Context, in *pb.UpdateStudentInfoReq) (*pb.UpdateStudentInfoResp, error) {
	l := logic.NewUpdateStudentInfoLogic(ctx, s.svcCtx)
	return l.UpdateStudentInfo(in)
}

func (s *UsercenterServer) UpdateTeacherInfo(ctx context.Context, in *pb.UpdateTeacherInfoReq) (*pb.UpdateTeacherInfoResp, error) {
	l := logic.NewUpdateTeacherInfoLogic(ctx, s.svcCtx)
	return l.UpdateTeacherInfo(in)
}

func (s *UsercenterServer) DeleteUserInfo(ctx context.Context, in *pb.DeleteUserInfoReq) (*pb.DeleteUserInfoResp, error) {
	l := logic.NewDeleteUserInfoLogic(ctx, s.svcCtx)
	return l.DeleteUserInfo(in)
}
