// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Account  string `json:"account"`
	Username string `json:"username"`
}

type VerCodeResp struct {
	Base64 string `json:"b64s"`
	Key    string `json:"key"`
}

type LoginReq struct {
	Account  string `json:"account"`
	PassWord string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	VerCode  string `json:"ver_code"`
	VerKey   string `json:"ver_key"`
	Account  string `json:"account"`
	PassWord string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
