// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type Course struct {
	CId     int64  `json:"c_id"`
	CName   string `json:"c_name"`
	Info    string `json:"info"`
	TeaId   int64  `json:"tea_id"`
	TeaName string `json:"tea_name"`
}

type SC struct {
	CId   int64  `json:"c_id"`
	CName string `json:"c_name"`
	StuId int64  `json:"stu_id"`
}

type TCourse struct {
	Course Course `json:"course"`
	Respon string `json:"respon"`
}

type GetCoursReq struct {
}

type GetCoursResp struct {
	Courses []Course `json:"course"`
}

type GetSearchCourseReq struct {
	CName string `path:"c_name"`
}

type GetSearchCourseResp struct {
	Courses []Course `json:"course"`
}

type GetECourseReq struct {
	StuId int64 `path:"stu_id"`
}

type GetECourseResp struct {
	Courses []Course `json:"course"`
}

type DeletSCourseReq struct {
	StuId int64 `json:"stu_id"`
	CId   int64 `json:"c_id"`
}

type DeletSCourseResp struct {
	Courses []Course `json:"course"`
}

type AddSCourseReq struct {
	StuId int64 `json:"stu_id"`
	CId   int64 `json:"c_id"`
}

type AddSCourseResp struct {
	Courses []Course `json:"course"`
}

type AddTCourseReq struct {
	Course Course `json:"course"`
}

type AddTCourseResp struct {
	TCourses []TCourse `json:"tcourse"`
}

type UpdateTCourseReq struct {
	Course Course `json:"course"`
}

type UpdateTCourseResp struct {
	TCourses []TCourse `json:"tcourse"`
}

type DeleteTCourseReq struct {
	TeaId int64 `json:"tea_id"`
	CId   int64 `json:"c_id"`
}

type DeleteTCourseResp struct {
	TCourses []TCourse `json:"tcourse"`
}

type GetTCourseReq struct {
	TeaId int64 `path:"tea_id""`
}

type GetTCourseResp struct {
	TCourses []TCourse `json:"tcourse"`
}
